version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/applepine1125/gcr-push-example
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
