version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.0.5
jobs:
  test:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/applepine1125/gcr-push-example
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  
workflows:
  version: 2
  test:
    jobs:
      - test
  master-build:
    jobs:
      - gcp-gcr/build_and_push_image:
          context: gcr-push-sample
          registry-url: asia.gcr.io
          image: sample-image
          tag: latest
          filters:
            branches:
              only: master
